### ISSUE TITLE
Improve project structure

### ISSUE THREAD

**Issue by jonatasbaldin** [jonatasbaldin/fin#8]
Yeah, I know, everything is in the root folder, but it works, ok? hahah

Anyway, totally need to change the project structure to something more robust.

**Comment by msalcantara** [comment]
any idea of what kind of project struct is better?

**Comment by VoyTechnology** [comment]
If you have a few final binaries (server, admin cli etc), then probably https://github.com/golang-standards/project-layout works well. Otherwise it's fine to keep the main in root, folder packages with single intent.

**Comment by jonatasbaldin** [comment]
Yeah, I've been reading about it and I'll keep this project as flat as possible now!

Thanks!
